config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  	resources :issues do
  		resources :comments
  	end

	root "issues#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :issues
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates_presence_of :content
	belongs_to :user
	belongs_to :issue
end

app/models/issue.rb
class Issue < ApplicationRecord
	validates_presence_of :title , :content
	belongs_to :user
	belongs_to :category
	has_many :comments , :dependent => :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :issues
   has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_issue
	def new
		@comment = @issue.comments.build 
	end

	def create
		@comment = @issue.comments.new( comment_params )
		@comment.user = current_user

		if @comment.save 
			flash[:notice] = "Comment created"	
			redirect_to issue_path(@issue)
		else
			render 'new'
		end
	end

	def edit
		@comment = @issue.comments.find(params[:id])
		# 缺少後端驗證
		if @comment.user != current_user
			flash[:alert] = "你只能修改自己的評論"
			redirect_to issue_path(@issue)
		end
	end

	def update
		@comment = @issue.comments.find(params[:id])
		# 缺少後端驗證
		if @comment.user != current_user
			flash[:alert] = "你只能修改自己的評論"
			redirect_to issue_path(@issue)
		else
			if @comment.update(comment_params)
				redirect_to issue_path(@issue)
			else
				render "edit"
			end
		end
	end

	def destroy
		@comment = @issue.comments.find(params[:id])
		# 缺少後端驗證
		if @comment.user != current_user
			flash[:alert] = "你只能刪除自己的評論"
		else
			@comment.destroy
			flash[:alert] = "event was deleted"
		end
		redirect_to issue_path(@issue)
	end

	private
	def find_issue
		@issue = Issue.find(params[:issue_id])
	end

	def comment_params 
		params.require(:comment).permit(:content)
	end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
	before_action :find_post, only: :show
	before_action :find_own_post , :only => [:edit, :destroy, :update]
	before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]

	def index
		#never all!
		@issues = Issue.page(params[:page]).includes(:user)
	end

	def new
		@issue = current_user.issues.build
	end

	def show
		@comment = Comment.new
		#never all!
		@comments = @issue.comments.includes(:user).page(params[:page])
	end

	def create
		@issue = current_user.issues.build(issue_params)

		if @issue.save
			flash[:notice] = "新增成功"
			redirect_to issue_path(@issue)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @issue.update(issue_params)
			flash[:notice] = "修改成功"
			redirect_to issue_path(@issue)
		else
			render "edit"
		end
	end

	def destroy
		flash[:notice] = "刪除成功"
		@issue.destroy
		redirect_to issues_path
	end

	private
	def find_post
		@issue = Issue.find(params[:id])
	end

	def find_own_post
		#刪除修改缺乏後端驗證
		@issue = current_user.issues.find(params[:id])
	end

	def issue_params
		params.require(:issue).permit(:title, :content, :category_id)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/comments/edit.html.erb
<%= form_for @comment, url: issue_comment_path(@issue, @comment) do |f| %>
    <% if @comment.errors.any? %>
        <ul>
          <% @comment.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>
    <%= f.label "Edit Content" %>
    <%= f.text_field :content %>
    <%= f.submit "Update" %>
<% end %>

<%= link_to "Back", issue_path(@issue) %>

app/views/issues/_form.html.erb
<% if @issue.errors.any? %>
    <ul>
      <% @issue.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
    </ul>
<% end %>
<table class="table">
	<tr>
		<td>
			<%= f.label :title %>
			<%= f.text_field :title %>
		</td>
	</tr>

	<tr>
		<td>
			<%= f.label :content %> 
			<%= f.text_area :content %>
		</td>
	</tr>
	<tr>
		<%= f.collection_select :category_id, Category.all, :id, :name, prompt: "Select a category" %>
	</tr>

</table>

app/views/issues/edit.html.erb
<h1>Edit <%= @issue.title %></h1>

<%= form_for @issue, url: issue_path(@issue), method: :patch do |f| %>
	<%= render :partial => 'form', :locals => { :f => f }  %>
	<%= f.submit class: "btn btn-default" %>
<%end %>

<%= link_to "Back", issue_path(@issue) %>

app/views/issues/index.html.erb
<div class="container">

	<h1>Disaster news</h1>
	<table class= "table">
		<tr>
			<td>Title </td>
			<td>Author</td>
			<td>Comment</td>
			<td>Last reply</td>
		</tr>
		<tbody>
			<% @issues.each do |issue| %>
			<tr>
				<td><%= link_to "#{issue.title}", issue_path(issue) %> <div class="btn btn-success"><%= issue.category.try(:name) %></div></td>
				<td><%= issue.user.email %></td>
				<td><%= issue.content %></td>
				<td><%= time_ago_in_words(issue.created_at) %></td>
			<% end %>
			</tr>
		</tbody>

	</table>
  <%= paginate @issues %>
	<% if current_user %>
		<%= link_to "New Post", new_issue_path %>
	<% end  %>
</div>

app/views/issues/new.html.erb
<div class="container">
<h1>New post</h1>
	<%= form_for @issue, url: issues_path do |f| %>
		<%= render :partial => 'form', :locals => { :f => f } %>
		<%= f.submit class: "btn btn-default" %>
		
	<%end %>

	<%= link_to "Home", issues_path, class: "btn btn-default" %>
</div>

app/views/issues/show.html.erb
<h1><%= @issue.title %></h1> 
<div class="btn btn-success"> <%= @issue.category.try(:name) %></div>

<div class="wrap container" style="background-color: #ccc;">
	<h3>Content</h3>
	<p><%= @issue.content %></p>
	<% if current_user == @issue.user %>
			<%= link_to "Edit post", edit_issue_path, class: "btn btn-default"%>
			<%= link_to "Delete post", issue_path(@issue), method: :delete, class: "btn btn-danger" %>
	<% end %>
</div>

<table class="table" >
	<tr>
		<td>Comment</td>
		<td>User</td>
	</tr>
	<tbody>
	<% @comments.each do |comment| %>
		<tr>
			<td>
				<%= comment.content  %>
			</td>
			<td>
				<%= comment.user.email %>
			</td>
			<td>
			<% if current_user == comment.user %>
					<%= link_to "Delete", issue_comment_path(@issue, comment), method: :delete %>
					<%= link_to "Edit", edit_issue_comment_path(@issue, comment) %>
			<% end %>

			</td>
		</tr>
	<% end %>
	</tbody>

</table>
<%= paginate @comments %>
	
	
	<% if current_user %>
		<%= form_for @comment, :url => issue_comments_path(@issue) do |f| %>
		<%= f.text_field :content %>
		<%= f.submit "Reply" %>
		<% end %>
	<% end  %>
<%= link_to "Home", issues_path, class:"btn btn-default" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Midterm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">     
      <% if current_user %>
        <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
        <%= link_to('修改密碼', edit_registration_path(:user)) %>
        <p style="float: right">Halo <%= current_user.email %></p>
      <% else %>
        <%= link_to('註冊', new_registration_path(:user)) %> |
        <%= link_to('登入', new_session_path(:user)) %>
      <% end %>


    	<p class="notice"><%= flash[:notice] %></p>
      <p class="alert"><%= flash[:alert] %></p>
      <%= yield %>
    </div>
  </body>
</html>